export type Temperature = 'Celsius' | 'Fahrenheit'
export type Speed = 'mph' | 'kmh'
export type Pressure = 'mm' | 'kpa'
export type Precipitation = 'mm' | 'inch'
export type Distance = 'km' | 'mile'
